
kind: Service 
apiVersion: v1 
metadata:
  name: netshell
spec:
  type: LoadBalancer
  selector:
    app: echo-on-port-8000 
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshell
  labels:
    app: echo-on-port-8000
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-on-port-8000
  strategy: {}
  template:
    metadata:
      labels:
        app: echo-on-port-8000
    spec:
      containers:
        - name: netshell
          image: highcanfly/net-tools:latest
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "cd ~/ && touch file.txt && mknod -m 777 fifo p && cat fifo | netcat -k -l 8000 > fifo && sleep infinity"]
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 250m
              memory: "536870912"
      restartPolicy: Always
status: {}