apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2023-03-24T07:37:54Z"
  labels:
    kubernetes.io/metadata.name: sandbox
  name: sandbox
---

apiVersion: v1
kind: Pod
metadata:
  name: shell
spec:
  containers:
  - name: shell
    image: highcanfly/net-tools
    imagePullPolicy: Always
    command: ["/bin/sh"]
    args: ["-c", "cd ~/ && touch file.txt && mknod -m 777 fifo p && cat fifo | netcat -k -l 8000 > fifo && sleep infinity"]
  hostNetwork: false
  dnsPolicy: ClusterFirst
